pub const MAX_SHADOW_CASCADES: usize = 4;
pub const DEFAULT_FRAMES_IN_FLIGHT: usize = 3;
pub const DEFAULT_SHADOW_MAP_RESOLUTION: u32 = 2048;
pub const DEFAULT_SHADOW_CASCADE_SPLITS: [f32; MAX_SHADOW_CASCADES + 1] =
    [0.1, 15.0, 40.0, 100.0, 300.0];
pub const MESHLET_MAX_VERTS: usize = 64;
pub const MESHLET_MAX_PRIMS: usize = 124;
pub const MESHLET_WORKGROUP_SIZE: u32 = 64;

// Back-compat defaults for legacy renderers.
pub const FRAMES_IN_FLIGHT: usize = DEFAULT_FRAMES_IN_FLIGHT;
pub const SHADOW_MAP_RESOLUTION: u32 = DEFAULT_SHADOW_MAP_RESOLUTION;
pub const NUM_CASCADES: usize = MAX_SHADOW_CASCADES;
pub const CASCADE_SPLITS: [f32; MAX_SHADOW_CASCADES + 1] = DEFAULT_SHADOW_CASCADE_SPLITS;
