use crate::graphics::common::{constants::MAX_SHADOW_CASCADES, renderer::ShaderConstants};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SkinningMode {
    Auto,
    Gpu,
    Cpu,
}

impl Default for SkinningMode {
    fn default() -> Self {
        SkinningMode::Auto
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TransparentSortMode {
    None,
    BackToFront,
    FrontToBack,
}

impl Default for TransparentSortMode {
    fn default() -> Self {
        TransparentSortMode::BackToFront
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SpriteLightingMode {
    Fragment,
    Vertex,
}

impl Default for SpriteLightingMode {
    fn default() -> Self {
        SpriteLightingMode::Fragment
    }
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct RenderConfig {
    pub gbuffer_pass: bool,
    pub shadow_pass: bool,
    pub direct_lighting_pass: bool,
    pub sky_pass: bool,
    pub ssgi_pass: bool,
    pub ssgi_denoise_pass: bool,
    pub ssr_pass: bool,
    pub ddgi_pass: bool,
    pub egui_pass: bool,
    pub gizmo_pass: bool,
    pub sprite_pass: bool,
    pub ui_pass: bool,
    pub sprite_picking: bool,
    pub transparent_pass: bool,
    pub text_world_pixels_per_unit: f32,
    pub text_world_raster_oversample: f32,
    pub text_world_raster_min_scale: f32,
    pub text_world_raster_max_scale: f32,
    pub text_world_glyph_max_raster_px: u32,
    pub text_world_raster_scale_step: f32,
    pub text_world_auto_quality: bool,
    pub text_world_auto_quality_min_factor: f32,
    pub text_world_auto_quality_max_factor: f32,
    pub text_layout_scale: f32,
    pub text_screen_layout_quantize: bool,
    pub text_world_layout_quantize: bool,
    pub text_min_font_px: f32,
    pub text_glyph_atlas_padding_px: u32,
    pub text_glyph_uv_inset_px: f32,

    pub freeze_render_camera: bool,

    pub max_lights_forward: usize,
    pub max_lights_deferred: usize,
    pub transparent_sort_mode: TransparentSortMode,
    pub sprite_lighting_mode: SpriteLightingMode,
    pub transparent_shadows: bool,
    pub alpha_cutoff_default: f32,

    pub frames_in_flight: u32,
    pub shadow_map_resolution: u32,
    pub shadow_cascade_count: u32,
    pub shadow_cascade_splits: [f32; MAX_SHADOW_CASCADES + 1],

    pub frustum_culling: bool,
    pub occlusion_culling: bool,
    pub lod: bool,
    pub single_resident_lod_per_mesh: bool,
    pub gpu_driven: bool,
    pub gpu_multi_draw_indirect: bool,
    pub render_bundles: bool,
    pub bundle_invalidate_on_resource_changes: bool,
    pub bundle_cache_stable_frames: u32,
    pub deterministic_rendering: bool,
    pub use_dont_care_load_ops: bool,
    pub use_mesh_shaders: bool,
    pub use_transient_textures: bool,
    pub use_transient_aliasing: bool,
    pub gpu_cull_depth_bias: f32,
    pub gpu_cull_rect_pad: f32,
    pub gpu_lod0_distance: f32,
    pub gpu_lod1_distance: f32,
    pub gpu_lod2_distance: f32,
    pub transform_epsilon: f32,
    pub rotation_epsilon: f32,
    pub cull_interval_frames: u32,
    pub lod_interval_frames: u32,
    pub streaming_interval_frames: u32,
    pub streaming_scan_budget: u32,
    pub streaming_request_budget: u32,
    pub streaming_allow_full_scan: bool,
    pub viewport_resize_debounce_ms: u32,
    pub occlusion_stable_pos_epsilon: f32,
    pub occlusion_stable_rot_epsilon: f32,

    pub rt_accumulation: bool,
    pub rt_samples_per_frame: u32,
    pub rt_max_bounces: u32,
    pub rt_direct_lighting: bool,
    pub rt_shadows: bool,
    pub rt_use_textures: bool,
    pub rt_texture_array_budget_bytes: u64,
    pub rt_texture_array_min_resolution: u32,
    pub rt_texture_array_max_resolution: u32,
    pub rt_exposure: f32,
    pub rt_max_accumulation_frames: u32,
    pub rt_camera_pos_epsilon: f32,
    pub rt_camera_rot_epsilon: f32,
    pub rt_scene_pos_quantize: f32,
    pub rt_scene_rot_quantize: f32,
    pub rt_scene_scale_quantize: f32,
    pub rt_direct_light_samples: u32,
    pub rt_firefly_clamp: f32,
    pub rt_env_intensity: f32,
    pub rt_sky_view_samples: u32,
    pub rt_sky_sun_samples: u32,
    pub rt_sky_multi_scatter_strength: f32,
    pub rt_sky_multi_scatter_power: f32,
    pub rt_shadow_bias: f32,
    pub rt_ray_bias: f32,
    pub rt_min_roughness: f32,
    pub rt_normal_map_strength: f32,
    pub rt_throughput_cutoff: f32,
    pub rt_transparency_max_skip: u32,
    pub rt_alpha_cutoff_scale: f32,
    pub rt_alpha_cutoff_bias: f32,
    pub rt_alpha_cutoff_min: f32,
    pub rt_skinning_bounds_pad: f32,
    pub rt_skinning_motion_scale: f32,
    pub rt_blas_leaf_size: u32,
    pub rt_tlas_leaf_size: u32,
    pub rt_ray_budget: u64,
    pub rt_min_pixel_budget: u64,
    pub rt_complexity_base: u64,
    pub rt_complexity_exponent: f32,
    pub rt_resolution_scale: f32,
    pub rt_adaptive_scale: bool,
    pub rt_adaptive_scale_min: f32,
    pub rt_adaptive_scale_max: f32,
    pub rt_adaptive_scale_down: f32,
    pub rt_adaptive_scale_up: f32,
    pub rt_adaptive_scale_recovery_frames: u32,

    pub ddgi_intensity: f32,
    pub ddgi_specular_scale: f32,
    pub ddgi_specular_confidence: f32,
    pub ddgi_probe_count_x: u32,
    pub ddgi_probe_count_y: u32,
    pub ddgi_probe_count_z: u32,
    pub ddgi_probe_spacing: f32,
    pub ddgi_probe_resolution: u32,
    pub ddgi_probe_update_stride: u32,
    pub ddgi_max_distance: f32,
    pub ddgi_normal_bias: f32,
    pub ddgi_visibility_normal_bias: f32,
    pub ddgi_visibility_spacing_bias: f32,
    pub ddgi_visibility_max_bias: f32,
    pub ddgi_visibility_receiver_bias: f32,
    pub ddgi_visibility_variance_scale: f32,
    pub ddgi_visibility_bleed_min: f32,
    pub ddgi_visibility_bleed_max: f32,
    pub ddgi_hysteresis: f32,
    pub ddgi_reservoir_temporal_weight: f32,
    pub ddgi_reservoir_spatial_weight: f32,
    pub ddgi_resample_diffuse_samples: u32,
    pub ddgi_resample_specular_samples: u32,
    pub ddgi_resample_spatial_samples: u32,
    pub ddgi_resample_spatial_radius: u32,
    pub ddgi_resample_reservoir_mix: f32,
    pub ddgi_resample_history_depth_threshold: f32,
    pub ddgi_resample_min_candidate_weight: f32,
    pub ddgi_resample_specular_cone_angle: f32,
    pub ddgi_reflection_roughness_start: f32,
    pub ddgi_reflection_roughness_end: f32,
    pub ddgi_reflection_strength: f32,
    pub ddgi_reflection_fallback_mix: f32,
    pub rt_reflections: bool,
    pub rt_reflection_samples_per_frame: u32,
    pub rt_reflection_direct_light_samples: u32,
    pub rt_reflection_direct_lighting: bool,
    pub rt_reflection_shadows: bool,
    pub rt_reflection_accumulation: bool,
    pub rt_reflection_max_accumulation_frames: u32,
    pub rt_reflection_resolution_scale: f32,
    pub rt_reflection_ray_budget: u64,
    pub rt_reflection_min_pixel_budget: u64,
    pub rt_reflection_complexity_base: u64,
    pub rt_reflection_complexity_exponent: f32,
    pub rt_reflection_interleave: u32,
    pub rt_reflection_history_weight: f32,
    pub rt_reflection_history_depth_threshold: f32,
    pub rt_reflection_denoise_radius: u32,
    pub rt_reflection_denoise_depth_sigma: f32,
    pub rt_reflection_denoise_normal_sigma: f32,
    pub rt_reflection_denoise_color_sigma: f32,

    pub skinning_mode: SkinningMode,
    pub skin_palette_capacity: u32,
    pub skin_palette_growth: f32,
    pub cpu_skinning_vertex_budget: u32,

    pub debug_flags: u32,

    pub shader_constants: ShaderConstants,
}

pub const DEBUG_FLAG_UNLIT: u32 = 1 << 0;
pub const DEBUG_FLAG_DIRECT: u32 = 1 << 1;
pub const DEBUG_FLAG_INDIRECT: u32 = 1 << 2;
pub const DEBUG_FLAG_REFLECTIONS: u32 = 1 << 3;
pub const DEBUG_FLAG_EMISSION: u32 = 1 << 4;
pub const DEBUG_FLAG_SKY: u32 = 1 << 5;

impl Default for RenderConfig {
    fn default() -> Self {
        RenderConfig {
            gbuffer_pass: true,
            shadow_pass: true,
            direct_lighting_pass: true,
            sky_pass: true,
            ssgi_pass: true,
            ssgi_denoise_pass: true,
            ssr_pass: true,
            ddgi_pass: true,
            egui_pass: true,
            gizmo_pass: true,
            sprite_pass: true,
            ui_pass: true,
            sprite_picking: true,
            transparent_pass: true,
            text_world_pixels_per_unit: 16.0,
            text_world_raster_oversample: 2.0,
            text_world_raster_min_scale: 1.0,
            text_world_raster_max_scale: 512.0,
            text_world_glyph_max_raster_px: 1024,
            text_world_raster_scale_step: 0.125,
            text_world_auto_quality: true,
            text_world_auto_quality_min_factor: 0.35,
            text_world_auto_quality_max_factor: 1.0,
            text_layout_scale: 1.0,
            text_screen_layout_quantize: true,
            text_world_layout_quantize: false,
            text_min_font_px: 0.01,
            text_glyph_atlas_padding_px: 2,
            text_glyph_uv_inset_px: 0.5,

            freeze_render_camera: false,

            max_lights_forward: 256,
            max_lights_deferred: 2048,
            transparent_sort_mode: TransparentSortMode::BackToFront,
            sprite_lighting_mode: SpriteLightingMode::Fragment,
            transparent_shadows: false,
            alpha_cutoff_default: 0.5,

            frames_in_flight: 3,
            shadow_map_resolution: 2048,
            shadow_cascade_count: 4,
            shadow_cascade_splits: [0.1, 15.0, 40.0, 100.0, 300.0],

            frustum_culling: true,
            occlusion_culling: true,
            lod: true,
            single_resident_lod_per_mesh: true,
            gpu_driven: true,
            gpu_multi_draw_indirect: true,
            #[cfg(target_arch = "wasm32")]
            render_bundles: false,
            #[cfg(not(target_arch = "wasm32"))]
            render_bundles: true,
            bundle_invalidate_on_resource_changes: true,
            bundle_cache_stable_frames: 3,
            deterministic_rendering: true,
            use_dont_care_load_ops: false,
            use_mesh_shaders: false,
            use_transient_textures: true,
            use_transient_aliasing: true,
            gpu_cull_depth_bias: 0.01,
            gpu_cull_rect_pad: 1.0,
            gpu_lod0_distance: 25.0,
            gpu_lod1_distance: 60.0,
            gpu_lod2_distance: 120.0,
            transform_epsilon: 0.0001,
            rotation_epsilon: 0.0001,
            cull_interval_frames: 1,
            lod_interval_frames: 1,
            streaming_interval_frames: 1,
            streaming_scan_budget: 2048,
            streaming_request_budget: 512,
            streaming_allow_full_scan: false,
            viewport_resize_debounce_ms: 120,
            occlusion_stable_pos_epsilon: 0.002,
            occlusion_stable_rot_epsilon: 1.0e-5,

            rt_accumulation: true,
            rt_samples_per_frame: 1,
            rt_max_bounces: 3,
            rt_direct_lighting: true,
            rt_shadows: true,
            rt_use_textures: true,
            rt_texture_array_budget_bytes: 128 * 1024 * 1024,
            rt_texture_array_min_resolution: 64,
            rt_texture_array_max_resolution: 256,
            rt_exposure: 1.0,
            rt_max_accumulation_frames: 0,
            rt_camera_pos_epsilon: 0.001,
            rt_camera_rot_epsilon: 1.0e-4,
            rt_scene_pos_quantize: 0.0001,
            rt_scene_rot_quantize: 0.0001,
            rt_scene_scale_quantize: 0.0001,
            rt_direct_light_samples: 1,
            rt_firefly_clamp: 0.0,
            rt_env_intensity: 1.0,
            rt_sky_view_samples: 6,
            rt_sky_sun_samples: 6,
            rt_sky_multi_scatter_strength: 0.0,
            rt_sky_multi_scatter_power: 1.0,
            rt_shadow_bias: 0.001,
            rt_ray_bias: 0.0005,
            rt_min_roughness: 0.02,
            rt_normal_map_strength: 1.0,
            rt_throughput_cutoff: 0.0,
            rt_transparency_max_skip: 8,
            rt_alpha_cutoff_scale: 1.0,
            rt_alpha_cutoff_bias: 0.0,
            rt_alpha_cutoff_min: 0.0,
            rt_skinning_bounds_pad: 0.25,
            rt_skinning_motion_scale: 1.0,
            rt_blas_leaf_size: 4,
            rt_tlas_leaf_size: 4,
            rt_ray_budget: 6_000_000,
            rt_min_pixel_budget: 4096,
            rt_complexity_base: 4096,
            rt_complexity_exponent: 0.5,
            rt_resolution_scale: 1.0,
            rt_adaptive_scale: true,
            rt_adaptive_scale_min: 0.1,
            rt_adaptive_scale_max: 1.0,
            rt_adaptive_scale_down: 0.85,
            rt_adaptive_scale_up: 1.02,
            rt_adaptive_scale_recovery_frames: 30,

            ddgi_intensity: 1.0,
            ddgi_specular_scale: 1.0,
            ddgi_specular_confidence: 0.8,
            ddgi_probe_count_x: 16,
            ddgi_probe_count_y: 8,
            ddgi_probe_count_z: 16,
            ddgi_probe_spacing: 3.0,
            ddgi_probe_resolution: 6,
            ddgi_probe_update_stride: 4,
            ddgi_max_distance: 40.0,
            ddgi_normal_bias: 0.2,
            ddgi_visibility_normal_bias: 0.2,
            ddgi_visibility_spacing_bias: 0.02,
            ddgi_visibility_max_bias: 0.5,
            ddgi_visibility_receiver_bias: 1.0,
            ddgi_visibility_variance_scale: 1.0,
            ddgi_visibility_bleed_min: 0.05,
            ddgi_visibility_bleed_max: 0.2,
            ddgi_hysteresis: 0.9,
            ddgi_reservoir_temporal_weight: 0.9,
            ddgi_reservoir_spatial_weight: 0.5,
            ddgi_resample_diffuse_samples: 4,
            ddgi_resample_specular_samples: 2,
            ddgi_resample_spatial_samples: 2,
            ddgi_resample_spatial_radius: 1,
            ddgi_resample_reservoir_mix: 0.5,
            ddgi_resample_history_depth_threshold: 0.01,
            ddgi_resample_min_candidate_weight: 1.0e-4,
            ddgi_resample_specular_cone_angle: 1.5707964,
            ddgi_reflection_roughness_start: 0.2,
            ddgi_reflection_roughness_end: 0.6,
            ddgi_reflection_strength: 1.0,
            ddgi_reflection_fallback_mix: 0.35,
            rt_reflections: false,
            rt_reflection_samples_per_frame: 1,
            rt_reflection_direct_light_samples: 1,
            rt_reflection_direct_lighting: true,
            rt_reflection_shadows: true,
            rt_reflection_accumulation: true,
            rt_reflection_max_accumulation_frames: 0,
            rt_reflection_resolution_scale: 0.5,
            rt_reflection_ray_budget: 3_000_000,
            rt_reflection_min_pixel_budget: 4096,
            rt_reflection_complexity_base: 4096,
            rt_reflection_complexity_exponent: 0.5,
            rt_reflection_interleave: 1,
            rt_reflection_history_weight: 0.9,
            rt_reflection_history_depth_threshold: 0.02,
            rt_reflection_denoise_radius: 2,
            rt_reflection_denoise_depth_sigma: 50.0,
            rt_reflection_denoise_normal_sigma: 16.0,
            rt_reflection_denoise_color_sigma: 6.0,

            skinning_mode: SkinningMode::Auto,
            skin_palette_capacity: 0,
            skin_palette_growth: 1.5,
            cpu_skinning_vertex_budget: 0,

            debug_flags: DEBUG_FLAG_DIRECT
                | DEBUG_FLAG_INDIRECT
                | DEBUG_FLAG_REFLECTIONS
                | DEBUG_FLAG_EMISSION
                | DEBUG_FLAG_SKY,

            shader_constants: ShaderConstants::default(),
        }
    }
}
